//
//  Enumerations.swift
//  SearchPoint
//
//  Created by Mobile Programming on 30/11/23.
//

import Foundation

// MARK: - USERDEFAULT KEYS

enum keyValue : String {
    case primaryGenoType = "priorityFirstBreedName"
    case secondaryGenoType = "secondaryFirstBreddingOutlet"
    case tertirayGenoType = "territoryFirstBreddingOutlet"
    case dataListPrimaryGenoType = "dataListPrimaryGenoType"
    case dataListSecondaryGenoType = "dataListSecondaryGenoType"
    case dataListTertirayGenoType = "dataListTertirayGenoType"
    case dataBeefBreedID = "dataBeefBreedID"
    case dataBeefBreedName = "dataBeefBreedName"
    case ADHFilterApplied = "ADHFilter"
    case providerID = "Pvid"
    case country = "country"
    case beefBreedID = "beefBreedID"
    case beefBreedName = "beefBreedName"
    case GenoBeefBreedName = "GenoBeefBreedName"
    case girlandoBreedId = "2b230527-6388-476b-84ae-84c019ea8600"
    case girlandoNewBreedId = "f91a971b-f2c0-4f8a-96a2-fc25188ae8f3"
    case searchByEarTagAnimal = "searchByEarTagAnimal"
    case isAnimalClickedFromBeefCart = "isAnimalClickedFromBeefCart"
    case isToUpdateAndAddAnimal = "isToUpdateAndAddAnimal"
    case mustRegisterDevice  = "mustRegisterDevice"
    case submitTypeSelection  = "submitTypeSelection"
    case brazilMarket = "BR"
    case marketName = "marketName"
    case collectorIdentifier = "collectorIdentifier"
    case dataEntryScreenSave = "dataEntryScreenSave"
    case savesex = "savesex"
    case todate = "todate"
    case fromdate = "fromdate"
    case lngId = "lngId"
    case lngCode = "lngCode"
    case isBarCodeIncrementalClear = "isBarCodeIncrementalClear"
    case barcodeIncremental = "barcodeIncremental"
    case provider = "provider"
    case contactSupport = "ContactSupport"
    case firstLogin = "FirstLogin"
    case userName = "userName"
    case beefPvid = "BeefPvid"
    case addedAnimal = "addedanimal"
    case dairySubmitBtnFlag = "dairySubmitBtnFlag"
    case userId = "userId"
    case orderIdBeef = "orderIdBeef"
    case autoIdBeef = "autoIdBeef"
    case productName = "productname"
    case emailBeef = "emailBeef"
    case showBeefProductTbl = "showbeefproductTbl"
    case identifyStore = "identifyStore"
    case review = "review"
    case beefBreed = "Beefbreed"
    case syncOff = "syncoff"
    case name = "name"
    case orderId = "orderId"
    case searchByAnimal = "searchByAnimal"
    case imageCount = "imageCount"
    case languageChanged = "languageChanged"
    case versionTxt = "versionTxt"
    case url = "url"
    case number = "number"
    case imageData = "imageData"
    case password = "password"
    case terms = "Terms"
    case accessToken = "accessToken"
    case mustValidateDevice = "mustValidateDevice"
    case firstName = "FirstName"
    case scannerSelection = "scannerSelection"
    case currentActiveCustomerId = "currentActiveCustomerId"
    case appleLanguages = "AppleLanguages"
    case creationDate = "creationDate"
    case deviceId = "DeviceId"
    case email = "email"
    case appId = "appId"
    case touchId = "touchID"
    case oflinesave = "oflinesave"
    case token = "Token"
    case farmValue = "farmValue"
    case notificationIdentifier = "NotificationIdentifier"
    case del = "del"
    case abc = "abc"
    case settingDefault = "settingDefault"
    case showbeefInheritTable = "showbeefInheritTable"
    case settingDone = "settingDone"
    case beefProduct = "beefProduct"
    case globalHD50K = "Global HD50K"
    case capsInherit = "INHERIT"
    case bfProductId = "BfProductId"
    case nonGenoType = "Non-Genotype"
    case genStarBlack = "GenStarblack"
    case genoTypeOnly = "Genotype Only"
    case genoTypeStarBlack = "GenotypeStarblack"
    case geneStarBlack = "GeneSTAR\u{00ae} Black"
    case brzGenoType = "BrazilGenotype"
    case page = "page"
    case onKey = "On"
    case chpid = "chpid"
    case userLogin = "userlogin"
    case pageNumber = "PageNumber"
    case checkOffline = "checkofline"
    case countAnimal = "countAnimal"
    case placeOrder = "placeOrder"
    case beefProductAdded = "beefProductAdded"
    case deleted = "deleted"
    case scrollIsEnable = "scrollIsEnable"
    case speciesId = "SpeciesId"
    case date = "date"
    case clarifideCDCBUS = "CLARIFIDE CDCB (US)"
    case providerNameUS = "providerNameUS"
    case clarifideCDCBBR = "CLARIFIDE CDCB (BR)"
    case currentActiveMarketId = "currentActiveMarketId"
    case ocrKey = "ocr"
    case rfidKey = "rfid"
    case beefScannerSelection = "beefScannerSelection"
    case providerName = "ProviderName"
    case USDairyProducts = "US Dairy Products"
    case beefProductID = "beefProductID"
    case inheritFOSampleTrackingDetailVC = "InheritFOSampleTrackingDetailVC"
    case inheritFOReviewOrderVC = "InheritFOReviewOrderVC"
    case officialId = "officialid"
    case brazilProduct = "brazilproduct"
    case pdId = "pdId"
    case beefTSU = "Beeftsu"
    case inheritBeefbreed = "InheritBeefbreed"
    case beefInheritTSU = "BeefInheritTsu"
    case autoId = "autoId"
    case isInhertDisabledForBrazil = "IsInhertDisabledForBrazil"
    case isGlobalHD50DisabledForBrazil = "IsGlobalHD50DisabledForBrazil"
    case nominatorSave = "NominatorSave"
    case screen = "screen"
    case fOSampleTrackingDetailVC = "FOSampleTrackingDetailVC"
    case foReviewOrderVC = "FOReviewOrderVC"
    case keyboardSelection = "keyboardSelection"
    case billToCustomerId = "billToCustomerId"
    case marketNameID = "marketNameID"
    case checkFilter = "checkfliter"
    case headerValue = "headervalue"
    case traitValue = "traitvalue"
    case traitName = "traitname"
    case sortOrder = "Sortorder"
    case idSelect = "idselect"
    case breedName = "breedname"
    case selectedProviderName = "selectedProviderName"
    case selectedProductName = "selectedProductName"
    case breedIndexPath = "breedIndexPath"
    case breedIndex = "breedindex"
    case isHerditySelected = "isHerditySelected"
    case inheritEnrollment = "InheritEnrollment"
    case brazil = "brazil"
    case gLobal = "GLobal"
    case clickAuProvider = "ClickAuProvider"
    case clarifideCDCBCan = "CLARIFIDE CDCB (CAN)"
    case clarifideAHDBUK = "CLARIFIDE AHDB (UK)"
    case isAuSelected = "isAuSelected"
    case auDairyProducts = "AU Dairy Products"
    case clarifideGirolandoBR = "CLARIFIDE Girolando (BR)"
    case clarifideCDCBBenelux = "CLARIFIDE CDCB (BeNeLux)"
    case clarifideCDCBIT = "CLARIFIDE CDCB (IT)"
    case farmId = "farmid"
    case holsteinUSA = "Holstein USA"
    case zoetis = "Zoetis"
    case numericKeyboard = "Numeric"
    case alphaNumericKeyboard = "alphaNumeric"
    case defaultDatePicker = "defaultDatePicker"
    case defaultEntry = "defaultEntry"
    case pickerMode = "pickerMode"
    case orderSlideTag = "orderSlideTag"
    case brazilBarcodeReviewVC = "brazilBarcodeReviewVC"
    case barcode = "barcode"
    case seriesReviewVC = "seriesReviewVC"
    case brazilBarcode = "brazilBarcode"
    case series = "series"
    case rgn = "rgn"
    case rgd = "rgd"
    case genotipagem = "Genotipagem"
    case animalId = "animalId"
    case productCount = "productCount"
    case breed = "breed"
    case bvdvValidation = "BVDVvalidation"
    case isAgreeForSubmit = "isAggreForSubmit"
    case submitBtnFlag = "SubmitBtnFlag"
    case beefDateEntrySaveReviewPreference = "BeefdateEntrySaveReviewPreference"
    case isProviderChange = "is_provider_change"
    case dataEntryListName = "dataEntryListName"
    case bvdvSelected = "BVDVSeleted"
    case noNeedAuPopUp = "NoNeedAuPopUp"
    case dataEntryHelpScreen = "dataEntryHelpScreen"
    case expandView = "expandView"
    case listId = "listId"
    case listIdSaveOnSelection = "ListIdSaveOnSelection"
    case listNameSaveOnSelection = "ListNameSaveOnSelection"
    case customerId = "customerId"
    case listName = "listName"
    case dataEntryListId = "dataEntryListId"
    case providerIdText = "providerId"
    case dateEntrySaveReviewPreference = "dateEntrySaveReviewPreference"
    case selectedPrimaryBreed = "selectedPrimaryBreed"
    case selectedSecondaryBreed = "selectedSecondaryBreed"
    case selectedTertiaryBreed = "selectedTertiaryBreed"
    case onFarmId = "OnFarmId"
    case officialTag = "OfficialTag"
    case deviceOrderId = "DeviceOrderId"
    case capsOrderId = "OrderId"
    case sampleBarCode = "SampleBarCode"
    case productId = "ProductId"
    case capsProviderId = "ProviderId"
    case capsUserId = "UserId"
    case isOffline = "IsOffline"
    case offline = "offline"
    case productDetails = "ProductDetails"
    case addOnId = "AddonId"
    case addOnDetails = "AddonDetails"
    case nominator = "Nominator"
    case capsDBName = "DBName"
    case dbName = "dbname"
    case isBarCodeIncremental = "isBarCodeIncremental"
    case dataEntryGirlandoSampleType = "DataEntryGirlandoSampleType"
    case matchedBarcodeFlag = "matchedBarcodeFlag"
    case timeStamp = "timeStamp"
    case dataEntryAnimalIdSelectionCart = "DataEntryAnimalIdSelectionCart"
    case applicationIdentifier = "ApplicationIdentifier"
    case capsBreedName = "breedName"
    case sampleId = "sampleId"
    case dataEntryGirlandoSampleTypeClear = "DataEntryGirlandoSampleTypeClear"
    case selectAnimalId = "selectAnimalId"
    case matchedBarcodeFlagDataEntry = "matchedBarcodeFlagDataEntry"
    case capsFarmId = "farmId"
    case sireIdSaveTemp = "SireIdSaveTemp"
    case naabIdSaveTemp = "NaabIdSaveTemp"
    case dataEntryTsuClear = "dataEntryTsuClear"
    case dataEntryTsu = "dataEntryTsu"
    case dataEntrybreedNameClear = "dataEntrybreedNameClear"
    case dataEntrybreedName = "dataEntrybreedName"
    case dataEntrybreedId = "dataEntrybreedId"
    case breedId = "breedId"
    case alpha2 = "alpha2"
    case threeCharCode = "threeCharCode"
    case alphaCode = "alphaCode"
    case naabCode = "naabCode"
    case numericCode = "numericCode"
    case bullID = "bullID"
    case sireNationalId = "sireNationalId"
    case dataEntrytissueBttn = "DataEntrytissueBttn"
    case dataEntrygenotypeTissueBttnClear = "DataEntrygenotypeTissueBttnClear"
    case dataEntrytissueBttnClear = "DataEntrytissueBttnClear"
    case dataEntryBeeftsuClear = "DataEntryBeeftsuClear"
    case dataEntryBeefInheritTsuClear = "DataEntryBeefInheritTsuClear"
    case dataEntryBeefbreedClear = "DataEntryBeefbreedClear"
    case dataEntryNZBeeftsuClear = "DataEntryNZBeeftsuClear"
    case dataEntryInheritBeefbreedClear = "DataEntryInheritBeefbreedClear"
    case dataEntryBeefInheritTsu = "DataEntryBeefInheritTsu"
    case dataEntryInheritBeefbreed = "DataEntryInheritBeefbreed"
    case dataEntryBeeftsu = "DataEntryBeeftsu"
    case dataEntryBeefbreed = "DataEntryBeefbreed"
    case pidKey = "pid"
    case dataEntrygenotypeTissueBttn = "DataEntrygenotypeTissueBttn"
    case dataEntryNZBeeftsu = "DataEntryNZBeeftsu"
    case beefAnimalIdSelectionCart = "BeefAnimalIdSelectionCart"
    case chkValue = "chkValue"
    case capsBrazil = "Brazil"
    case priorityBreedName = "priorityBreedName"
    case beefSireReg = "BeefSireReg"
    case beefDamReg = "BeefDamReg"
    case beefBreedReg = "BeefBreedReg"
    case beefRegAssociation = "BeefRegAssociation"
    case NZBeefBreedReg = "NZBeefBreedReg"
    case NZBeefbreed = "NZBeefbreed"
    case tissueIdSaveLast = "tissueIdSaveLast"
    case selectedAnimalBreedID = "selectedAnimalBreedID"
    case scrollIncrement = "scrollIncrement"
    case headerName = "headerName"
    case myHerdListSelectIndex = "myHerdListSelectIndex"
    case myHerdOfficalid = "myherdofficalid"
    case myHerdOnfarmId = "myherdonfarmid"
    case groupOnFormId = "grouponformid"
    case groupName = "groupName"
    case groupDetails = "groupdetails"
    case radioButtonCheck = "radioButtonCheck"
    case checkGroupIcon = "checkgroupicon"
    case checkGroup = "checkgroup"
    case groupKey = "group"
    case checkIndex = "checkindex"
    case smallGroupName = "groupname"
    case resultproviderID = "ResultproviderID"
    case resultBreedID = "ResultbreedID"
    case sexvalue = "sexvalue"
    case fromManagement = "FromManagment"
    case groupOnAnimalId = "grouponanimalid"
    case notes = "notes"
    case messageKey = "message"
    case photoBase64Encoded = "photoBase64Encoded"
    case newBackScreenIndex = "newbackscreenindex"
    case groupNameSave = "groupnamesave"
    case groupStatus = "groupstatus"
    case groupTypeId = "grouptypeid"
    case groupId = "groupId"
    case errorDetail = "errorDetail"
    case groupServerId = "groupServerId"
    case checkActiveInactive = "checkactive/inactive"
    case filterTotalAnimalAccount = "filterTotalAnimalAccount"
    case filterMinDOB = "filterMinDOB"
    case filterMaxDOB = "filterMaxDOB"
    case checkDate = "checkdate"
    case newKey = "new"
    case todatefromate = "todatefromate"
    case fromdatefromate = "fromdatefromate"
    case animalReceivedCount = "AnimalReceivedCount"
    case emailMe = "emailMe"
    case beefEmailCheckValue = "beefemailcheckvalue"
    case submitKey = "submit"
    case beefPlaceOrderCheck = "beefplaceordercheck"
    case emailCheckValue = "emailcheckValue"
    case placeOrderCheck = "placeordercheck"
    case submitBtnFlagNew = "SubmitBtnFlagNew"
    case smallProductId = "productId"
    case beefBVDVSeleted = "BeefBVDVSeleted"
    case emailFlag = "emailFlag"
    case genotypeKey = "Genotype"
    case submitFlag = "submitFlag"
    case genotypeTissueBttn = "genotypeTissueBttn"
    case nzBeefTSU = "NZBeeftsu"
    case genotypeTissueBttnClear = "genotypeTissueBttnClear"
    case tissueBttnClear = "tissueBttnClear"
    case nzBeeftsuClear = "NZBeeftsuClear"
    case beeftsuClear = "BeeftsuClear"
    case beefbreedClear = "BeefbreedClear"
    case beefInheritTsuClear = "BeefInheritTsuClear"
    case inheritBeefbreedClear = "InheritBeefbreedClear"
    case tissueBttn = "tissueBttn"
    case girlandoSampleType = "GirlandoSampleType"
    case tsuClear = "tsuClear"
    case girlandoSampleTypeClear = "GirlandoSampleTypeClear"
    case breedNameClear = "breedNameClear"
    case tsuKey = "tsu"
    case animalIdSelectionCart = "AnimalIdSelectionCart"
    case marketCode = "marketCode"
    case radio1Key = "radio1"
    case radio2Key = "radio2"
    case earTagKey = "earTag"
    case orderIDRIKey = "orderIDRI"
    case smallOnFarmId = "onFarmId"
    case smallSampleBarcode = "sampleBarcode"
    case smallOfficialTag = "officialTag"
    case emailOrder = "E-Mail Order"
    case textValueEnglish = "textValueEnglish"
    case textValuePortugese = "textValuePortugese"
    case textValueItalian = "textValueItalian"
    case capsOfficialId = "officialId"
    case isBarCodeMatched = "isBarCodeMatched"
    case beefInheritSampleType = "BeefInheritSampleType"
    case tsuKeyType = "Tsu"
    case to_date_adh = "to_date_adh"
    case from_date_adh = "from_date_adh"
    case breedindexADH = "breedindexADH"
    case totalAnimalsCount = "totalanimalscount"
    case placeOrderText = "placeorder"
    case checkValue = "checkvalue"
    case serverAnimalId = "serverAnimalId"
    case capsTSUClear = "TsuClear"
    case addDealerCodeCheck = "addDealerCodeCheck"
    case dealerCode = "dealerCode"
}


// MARK: - APP HELP SCREEN NAMES

enum ScreenNames : String{
    
    case actionsRequired = "actionRequired"
    case contactSupport = "contactSupport"
    case dashboard = "dashboard"
    case dataEntry = "dataEntry"
    case addAnimal = "addAnimal"
    case addAnimalBeef = "addAnimalBeef"
    case orderingDefault = "orderingDefault"
    case resultHelp = "resultHelp"
    case trackSamples = "trackSamples"
    case menu = "navigation"
    case productSelectionReview = "productSelectionReview"
    case reviewVC = "reviewVc"
    case sampleTrackVC = "SampleTrackVC"

}

// MARK: - COUNTRY NAMES

enum countryName {
    
    case Belgium
    case Netherlands
    case Luxembourg
    
    var title: String {
        switch self {
        case .Belgium:
            return "Belgium"
        case .Netherlands:
            return "Netherlands"
        case .Luxembourg:
            return "Luxembourg"
        }
    }
}

// MARK: - DAIRY OR BEEF NAME TYPE

enum marketNameType : String {
    case Dairy = "Dairy"
    case Beef = "Beef"
}

// MARK: - DIRECTIONS
enum Direction {
    case top
    case bottom
    case center
    case left
    case right
}


//MARK: BORN TYPES
enum BornTypes: Int {
    case Single = 0
    case Multiple_Birth = 1
    case ET = 2
    case Split_Embryo = 3
    case Clone = 4
    case Internal = 5
}
